-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'ORGANIZATION_QUOTA_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE 'ORGANIZATION_OWNER_TRANSFERRED';
ALTER TYPE "AuditEventType" ADD VALUE 'ORGANIZATION_DELETED';
