-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'USER_SUSPENDED';
ALTER TYPE "AuditEventType" ADD VALUE 'USER_UNSUSPENDED';
ALTER TYPE "AuditEventType" ADD VALUE 'ADMIN_ROLE_GRANTED';
ALTER TYPE "AuditEventType" ADD VALUE 'ADMIN_ROLE_REVOKED';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "isSystemAdmin" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isSuspended" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "suspendedAt" TIMESTAMP(3);
